insert into art_style values ("Oil Painting", "Rich, textured strokes using oil-based paints, often creating depth and vivid color palettes.");
insert into art_style values ("Watercolor", "Delicate and translucent layers of paint, known for its fluidity and blending properties.");
insert into art_style values ("Acrylic Pouring", "Abstract technique where acrylic paints are poured onto a canvas, creating unique patterns as they mix and flow.");
insert into art_style values ("Digital Painting", "Art created using digital tools, mimicking traditional painting techniques but with the flexibility of a digital medium.");
insert into art_style values ("Mixed Media Collage", "Artwork incorporating various materials like paper, fabric, and found objects to create a textured and layered composition.");
insert into art_style values ("Pen and Ink", "Precise line drawings using ink, often featuring intricate details and cross-hatching.");
insert into art_style values ("Charcoal Sketch", "Drawings created with charcoal, known for their expressive and bold strokes.");
insert into art_style values ("Gouache Illustration", "Similar to watercolor but with a more opaque and vibrant finish, often used for detailed illustrations.");
insert into art_style values ("Scratchboard Art", "Illustrations created by scratching away a black surface to reveal a white layer underneath, producing high-contrast images.");
insert into art_style values ("Impasto Technique", "Thick and textured application of paint, creating a three-dimensional effect on the canvas.");
insert into art_style values ("Landscape Painting", "Depiction of natural scenery, capturing the essence of different environments through various painting techniques.");
insert into art_style values ("Abstract Expressionist Painting", "Emphasizes spontaneous and emotional expression, often featuring bold colors and gestural brushstrokes.");
insert into art_style values ("Geometric Design", "Art and design based on precise shapes, patterns, and mathematical principles.");
insert into art_style values ("Typography Art", "Creative arrangement of text elements to form artistic and visually appealing compositions.");
insert into art_style values ("Vector Illustration", "Graphics created using mathematical equations to represent images, allowing for scalability without loss of quality.");
insert into art_style values ("Photorealistic Rendering", "Artistic technique aiming to replicate reality with meticulous attention to detail, often seen in digital or traditional mediums.");
insert into art_style values ("Minimalist Design", "Stripped-down design focusing on simplicity, using minimal elements to convey a message or idea.");
insert into art_style values ("Botanical Illustration", "Detailed and accurate depictions of plant life, often used for scientific or artistic purposes.");
insert into art_style values ("Children's Book Illustration", "Whimsical and colorful illustrations tailored for children's literature, often featuring playful characters and scenes.");
insert into art_style values ("Fantasy Art", "Imaginative and otherworldly scenes often featuring mythical creatures, magic, and surreal landscapes.");
insert into art_style values ("Art Deco Design", "Stylish and ornamental design style from the early 20th century, characterized by geometric shapes and bold colors.");
insert into art_style values ("Vintage Poster Art", "Illustrations and designs reminiscent of classic posters from past eras, often featuring bold typography and graphics.");
insert into art_style values ("Cartoon Illustration", "Playful and exaggerated drawings, often featuring simplified characters with expressive features.");
insert into art_style values ("Scientific Illustration", "Precise and detailed drawings used to communicate scientific concepts or anatomical features.");
insert into art_style values ("Street Art Mural", "Large-scale, often graffiti-inspired artwork created in public spaces, conveying social or political messages.");
insert into art_style values ("Cubist Design", "Artistic style that portrays subjects from multiple viewpoints simultaneously, breaking them down into geometric shapes.");
insert into art_style values ("Pixel Art", "Digital art form that uses tiny, pixel-sized squares to create images, reminiscent of early video game graphics.");
insert into art_style values ("Surrealistic Painting", "Artistic style that explores dreamlike and subconscious imagery, often featuring fantastical and unexpected elements.");
insert into art_style values ("Pop Art Illustration", "Artistic movement that incorporates popular culture imagery and bright colors, often with a sense of irony.");
insert into art_style values ("Textile Design", "Patterns and designs created for fabrics, often featuring repeating motifs and intricate details suitable for textiles.");
insert into art_style values ("Stencil Art", "Creation of images by applying pigment to a surface through a cut-out template, resulting in crisp, defined shapes.");
insert into art_style values ("Engraving Technique", "Art created by incising a design onto a hard, flat surface, typically used for printmaking.");
insert into art_style values ("Neon Art", "Bright and vibrant art created using neon lights, often associated with contemporary and urban aesthetics.");
insert into art_style values ("Woodblock Printing", "Traditional printmaking technique where a design is carved into a wood block and then used to make prints.");
insert into art_style values ("Mosaic Art", "Creation of images by arranging small, colored pieces (tiles or glass) into a pattern or picture.");
insert into art_style values ("Steampunk Design", "Aesthetic inspired by steam-powered machinery and 19th-century industrial design, often featuring gears and brass elements.");
insert into art_style values ("Trompe-l'oeil Painting", "Art that creates the illusion of three-dimensionality, tricking the viewer into believing the depicted objects are real.");
insert into art_style values ("Calligraphy Art", "Elegant and expressive writing as an art form, often used for decorative and ornamental purposes.");
insert into art_style values ("Comic Book Art", "Illustrations and panels used in comic books, often featuring dynamic action and narrative storytelling.");
insert into art_style values ("Decoupage", "Artistic technique of decorating surfaces by applying cutouts from magazines or colored paper and sealing them with layers of varnish.");
insert into art_style values ("Kinetic Sculpture", "Sculptures that incorporate movement or elements that change over time, creating dynamic and interactive art.");
insert into art_style values ("Chiaroscuro Painting", "Use of strong contrasts between light and dark to create a sense of volume and three-dimensionality in paintings.");
insert into art_style values ("Futurist Art", "Artistic movement emphasizing speed, technology, and the dynamism of modern life, often featuring fragmented forms.");
insert into art_style values ("Stained Glass Art", "Art created by assembling colored glass pieces into intricate patterns, often used in windows and decorative items.");
insert into art_style values ("Folk Art", "Traditional and cultural art created by non-professional artists, often reflecting local customs and beliefs.");
insert into art_style values ("Art Brut (Outsider Art)", "Raw and untrained artistic expression, often created by self-taught artists outside of mainstream art institutions.");
insert into art_style values ("Glitch Art", "Artistic use of digital or analog glitches, errors, or imperfections to create visually striking and unconventional images.");
insert into art_style values ("Real-time 3D Rendering", "Creation of images or animations in real-time using computer graphics, often used in video games and simulations.");
insert into art_style values ("Reverse Glass Painting", "Artistic technique where the image is painted on the reverse side of a piece of glass, creating a glossy and translucent effect.");
insert into art_style values ("Tapestry Art", "Woven textile art, often depicting intricate scenes or patterns, with historical significance in storytelling and decoration.");
insert into art_style values ("Renaissance Italian Frescoes", "Mural paintings on wet plaster, characterized by meticulous details and classical themes, prominent during the Italian Renaissance.");
insert into art_style values ("Edo Period Japanese Ukiyo-e", "Woodblock prints depicting scenes of the 'floating world,' featuring kabuki actors, landscapes, and beautiful women.");
insert into art_style values ("Dutch Golden Age Still Life", "Detailed and symbolic still life paintings from the 17th century Netherlands, often featuring flowers, food, and luxury items.");
insert into art_style values ("Mughal Miniature Painting", "Intricate and detailed paintings from the Mughal Empire in South Asia, often portraying courtly life and historical events.");
insert into art_style values ("Baroque Spanish Bodegón", "Still life paintings in 17th-century Spain, showcasing everyday objects and food items with a realistic and dramatic flair.");
insert into art_style values ("Joseon Dynasty Korean Minhwa", "Traditional Korean folk art known for vibrant colors and symbolic depictions, often used for storytelling and decoration.");
insert into art_style values ("Colonial American Folk Art", "Naive and colorful art created in the American colonies, often depicting daily life, animals, and patriotic themes.");
insert into art_style values ("Russian Constructivism", "Avant-garde art movement in early 20th-century Russia, emphasizing geometric shapes and abstract compositions in design and architecture.");
insert into art_style values ("Indonesian Batik Art", "Traditional wax-resist dyeing technique on fabric, often featuring intricate patterns and cultural motifs.");
insert into art_style values ("Mayan Mural Art", "Ancient Mayan paintings on walls and pottery, portraying mythological narratives, religious ceremonies, and daily life.");
insert into art_style values ("Hanbok Fashion Illustration", "Contemporary South Korean fashion illustration featuring the traditional Hanbok garment in modern and creative contexts.");
insert into art_style values ("Islamic Geometric Art", "Art and design featuring intricate geometric patterns, commonly found in Islamic architecture, manuscripts, and textiles.");
insert into art_style values ("Heian Period Japanese Emakimono", "Illustrated handscrolls from Japan's Heian period, depicting narrative scenes and tales with delicate brushwork.");
insert into art_style values ("Romanticism German Nazarene Movement", "19th-century German art movement emphasizing religious and medieval themes, rejecting Neoclassical ideals.");
insert into art_style values ("Cuban Poster Art", "Bold and colorful graphic design in mid-20th-century Cuba, often associated with revolutionary and cultural themes.");
insert into art_style values ("Safavid Persian Carpet Design", "Intricate patterns and motifs found in Persian carpets, reflecting Persian art and craftsmanship traditions.");
insert into art_style values ("Canadian Inuit Printmaking", "Artistic expression through printmaking among the Inuit people, often depicting Arctic landscapes, wildlife, and cultural stories.");
insert into art_style values ("Taisho Period Japanese Modernism", "Artistic movement in early 20th-century Japan, combining traditional and modern elements in response to societal changes.");
insert into art_style values ("Ancient Egyptian Hieroglyphic Art", "Artwork featuring symbolic and pictorial representations in the form of hieroglyphs, common in ancient Egyptian tombs and temples.");
insert into art_style values ("Bauhaus German Design", "Modernist design movement in early 20th-century Germany, emphasizing functionality, simplicity, and the integration of art and technology.");
insert into art_style values ("Australian Aboriginal Dot Painting", "Indigenous Australian art form using dots to create intricate patterns and stories, often inspired by Dreamtime narratives.");
insert into art_style values ("Impressionist French Plein Air", "Outdoor painting style popularized in 19th-century France, capturing fleeting moments and atmospheric effects.");
insert into art_style values ("Byzantine Iconography", "Religious art from the Byzantine Empire, characterized by flat, symbolic depictions of saints and religious figures.");
insert into art_style values ("Postcolonial Nigerian Nsibidi Art", "Graphic and symbolic art from Nigeria, using Nsibidi symbols to convey information and cultural meanings.");
insert into art_style values ("Flemish Northern Renaissance", "Artistic style in Northern Europe during the Renaissance, known for meticulous detail and realistic representation.");
insert into art_style values ("Soviet Propaganda Art", "Artistic style in the Soviet Union, featuring bold graphics and slogans to promote political ideology and social messages.");
insert into art_style values ("Maori Whakairo Carving", "Traditional wood carving of the Maori people in New Zealand, often featuring intricate patterns and symbolic elements.");
insert into art_style values ("Pre-Columbian Peruvian Nazca Pottery", "Artistic ceramics from ancient Peru, featuring elaborate geometric and zoomorphic designs.");
insert into art_style values ("Post-Impressionist French Nabis Movement", "Artistic movement emphasizing symbolism, color, and decorative elements in late 19th-century France.");
insert into art_style values ("Modern Indian Madhubani Painting", "Traditional folk art from India, known for intricate geometric patterns and vibrant depictions of nature and mythology.");
insert into art_style values ("Medieval Celtic Manuscript Illumination", "Illustrated manuscripts from medieval Celtic cultures, featuring intricate patterns and stylized figures.");
insert into art_style values ("Ancient Greek Black-Figure Pottery", "Pottery from ancient Greece with black figures on a red background, depicting mythological scenes and everyday life.");
insert into art_style values ("Ndebele South African Mural Art", "Bold and colorful mural art from the Ndebele people, often featuring geometric patterns and vibrant hues.");
insert into art_style values ("Colonial Mexican Retablo Art", "Small devotional paintings from colonial Mexico, often featuring religious figures and scenes on wooden panels.");
insert into art_style values ("Edo Period Japanese Rimpa School", "Artistic school in Japan emphasizing decorative and vibrant compositions, often featuring nature themes.");
insert into art_style values ("Rococo French Boucher Style", "Artistic style in 18th-century France, characterized by ornate and playful depictions of pastoral scenes and romance.");
insert into art_style values ("Pueblo Native American Pottery", "Traditional pottery from Pueblo cultures in the southwestern United States, featuring intricate designs and symbolism.");
insert into art_style values ("Post-Revolutionary Mexican Muralism", "Mural art in Mexico following the Mexican Revolution, conveying social and political messages.");
insert into art_style values ("Ancient Roman Frescoes", "Wall paintings from ancient Rome, often depicting mythological scenes, landscapes, and daily life.");
insert into art_style values ("Swiss International Typographic Style", "Design movement in Switzerland emphasizing clean lines, sans-serif typography, and grid-based layouts in graphic design.");
insert into art_style values ("Van Gogh's Post-Impressionism", "Characterized by bold colors, swirling brushstrokes, and emotional intensity, as seen in Vincent van Gogh's works like 'Starry Night.'");
insert into art_style values ("Picasso's Cubism", "Innovative art movement initiated by Pablo Picasso and Georges Braque, featuring fragmented and abstracted forms in paintings such as 'Les Demoiselles d'Avignon.'");
insert into art_style values ("Dali's Surrealism", "Salvador Dali's artistic style known for dreamlike and bizarre imagery, as seen in works like 'The Persistence of Memory.'");
insert into art_style values ("Klimt's Art Nouveau", "Gustav Klimt's decorative and ornate style, characterized by intricate patterns, symbolism, and gold leaf, seen in paintings like 'The Kiss.'");
insert into art_style values ("Hokusai's Ukiyo-e", "Katsushika Hokusai's Japanese woodblock prints, particularly his iconic series 'Thirty-Six Views of Mount Fuji,' showcasing landscapes and nature.");
insert into art_style values ("Warhol's Pop Art", "Andy Warhol's art movement focusing on mass culture and consumerism, using repetitive images of everyday objects and celebrities.");
insert into art_style values ("O'Keeffe's Precisionism", "Georgia O'Keeffe's style known for precise, sharply defined forms, often featuring enlarged flowers and New Mexican landscapes.");
insert into art_style values ("Kandinsky's Abstract Art", "Wassily Kandinsky's pioneering work in abstract art, characterized by non-representational forms and vibrant colors.");
insert into art_style values ("Matisse's Fauvism", "Henri Matisse's style featuring bold colors, simplified forms, and a focus on emotional expression, as seen in works like 'Woman with a Hat.'");
insert into art_style values ("Rothko's Color Field Painting", "Mark Rothko's abstract style emphasizing large color fields, aiming to evoke emotional and contemplative responses.");
insert into art_style values ("Escher's Op Art", "Maurits Cornelis Escher's use of optical illusions and mathematical concepts in his intricate and mind-bending drawings.");
insert into art_style values ("Rembrandt's Baroque Realism", "Rembrandt's realistic and dramatic Baroque style, known for masterful use of light and shadow, as seen in portraits like 'The Night Watch.'");
insert into art_style values ("Haring's Street Art", "Keith Haring's graffiti-inspired street art, featuring bold lines and iconic symbols, conveying social and political messages.");
insert into art_style values ("Rousseau's Naïve Art", "Henri Rousseau's primitive and dreamlike style, characterized by fantastical landscapes and exotic scenes.");
insert into art_style values ("Pollock's Abstract Expressionism", "Jackson Pollock's drip painting technique and spontaneous approach, a hallmark of the Abstract Expressionist movement.");
insert into art_style values ("Hockney's Photorealism", "David Hockney's attention to detail and use of photography-inspired techniques in creating realistic paintings, such as 'A Bigger Splash.'");
insert into art_style values ("Whistler's Tonalism", "James McNeill Whistler's atmospheric and moody style, emphasizing tonal harmony and muted colors, as seen in 'Nocturne in Black and Gold.'");
insert into art_style values ("Monet's Impressionism", "Claude Monet's innovative use of color and light in capturing fleeting moments, a key figure in the Impressionist movement.");
insert into art_style values ("Kahlo's Surreal Self-Portraits", "Frida Kahlo's emotionally charged self-portraits, often featuring symbolism and elements of Mexican folk art.");
insert into art_style values ("Michelangelo's High Renaissance", "Michelangelo Buonarroti's monumental and classical art, seen in works like the frescoes of the Sistine Chapel.");
insert into art_style values ("Munch's Symbolism", "Edvard Munch's Symbolist style, known for emotionally charged and symbolic depictions, such as 'The Scream.'");
insert into art_style values ("Vermeer's Dutch Golden Age Realism", "Johannes Vermeer's realistic and meticulously detailed genre paintings, notable for their use of light and shadow.");
insert into art_style values ("Seurat's Pointillism", "Georges Seurat's technique of using small dots of color to create a larger image, as seen in 'A Sunday Afternoon on the Island of La Grande Jatte.'");
insert into art_style values ("Degas's Impressionist Ballet Scenes", "Edgar Degas's focus on capturing the energy and movement of ballet dancers in his Impressionist paintings.");
insert into art_style values ("Botticelli's Early Renaissance", "Sandro Botticelli's graceful and idealized depictions of figures, prominent in works like 'The Birth of Venus.'");
insert into art_style values ("Chagall's Surreal Folk Art", "Marc Chagall's dreamlike and folk-inspired style, featuring fantastical elements and vibrant colors, as seen in 'I and the Village.'");
insert into art_style values ("Bruegel's Flemish Renaissance Landscapes", "Pieter Bruegel the Elder's detailed landscapes and genre scenes, capturing the daily life of the Flemish Renaissance.");
insert into art_style values ("Rockwell's American Illustration", "Norman Rockwell's nostalgic and narrative illustrations, often depicting idealized scenes of American life.");
insert into art_style values ("Hokusai's Manga Sketches", "Katsushika Hokusai's quick and expressive sketches, showcasing a variety of subjects, from nature to everyday life.");
insert into art_style values ("Klee's Abstract Expressionism", "Paul Klee's playful and colorful abstract style, known for his use of geometric shapes and symbolic elements.");
insert into art_style values ("Bacon's Figurative Expressionism", "Francis Bacon's emotionally charged and distorted figurative paintings, exploring themes of existentialism and brutality.");
insert into art_style values ("Verrocchio's Italian Renaissance Sculpture", "Andrea del Verrocchio's Renaissance sculptures, known for their classical influences and attention to anatomy.");
insert into art_style values ("Miro's Surreal Abstraction", "Joan Miró's whimsical and abstract style, featuring playful shapes and symbols, as seen in 'The Tilled Field.'");
insert into art_style values ("Titian's Venetian Renaissance", "Tiziano Vecellio's rich and luxurious style, notable for his use of color and his mastery of portraiture and mythology.");
insert into art_style values ("Haring's Pop Street Art", "Keith Haring's graffiti-inspired street art, featuring bold lines and iconic symbols, conveying social and political messages.");
insert into art_style values ("Cézanne's Post-Impressionist Still Lifes", "Paul Cézanne's explorations of form and color in still life paintings, laying the groundwork for Cubism.");
insert into art_style values ("Goya's Romanticism", "Francisco Goya's dark and emotional depictions of war, societal issues, and fantastical themes during the Romantic era.");
insert into art_style values ("Lichtenstein's Pop Art Comic Strips", "Roy Lichtenstein's use of comic book-style imagery and techniques in creating fine art paintings.");
insert into art_style values ("Caravaggio's Baroque Chiaroscuro", "Michelangelo Merisi da Caravaggio's dramatic use of light and shadow, influencing Baroque painting.");
